# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scheduler.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'scheduler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fscheduler.proto\x12\x03\x63\x61m\"4\n\x03Job\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08priority\x18\x02 \x01(\x05\x12\x0f\n\x07payload\x18\x03 \x01(\t\"\'\n\x0e\x45nqueueRequest\x12\x15\n\x03job\x18\x01 \x01(\x0b\x32\x08.cam.Job\"\x0e\n\x0c\x45nqueueReply\"\x10\n\x0e\x44\x65queueRequest\"%\n\x0c\x44\x65queueReply\x12\x15\n\x03job\x18\x01 \x01(\x0b\x32\x08.cam.Job\"6\n\x13ReprioritiseRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0bnewPriority\x18\x02 \x01(\x05\"\x13\n\x11ReprioritiseReply2\xb3\x01\n\tScheduler\x12\x31\n\x07\x45nqueue\x12\x13.cam.EnqueueRequest\x1a\x11.cam.EnqueueReply\x12\x31\n\x07\x44\x65queue\x12\x13.cam.DequeueRequest\x1a\x11.cam.DequeueReply\x12@\n\x0cReprioritise\x12\x18.cam.ReprioritiseRequest\x1a\x16.cam.ReprioritiseReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scheduler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOB']._serialized_start=24
  _globals['_JOB']._serialized_end=76
  _globals['_ENQUEUEREQUEST']._serialized_start=78
  _globals['_ENQUEUEREQUEST']._serialized_end=117
  _globals['_ENQUEUEREPLY']._serialized_start=119
  _globals['_ENQUEUEREPLY']._serialized_end=133
  _globals['_DEQUEUEREQUEST']._serialized_start=135
  _globals['_DEQUEUEREQUEST']._serialized_end=151
  _globals['_DEQUEUEREPLY']._serialized_start=153
  _globals['_DEQUEUEREPLY']._serialized_end=190
  _globals['_REPRIORITISEREQUEST']._serialized_start=192
  _globals['_REPRIORITISEREQUEST']._serialized_end=246
  _globals['_REPRIORITISEREPLY']._serialized_start=248
  _globals['_REPRIORITISEREPLY']._serialized_end=267
  _globals['_SCHEDULER']._serialized_start=270
  _globals['_SCHEDULER']._serialized_end=449
# @@protoc_insertion_point(module_scope)
